### ISSUE TITLE
f3vanilla requests 4 populations

### ISSUE THREAD

**Issue by TCLamnidis** [pontussk/popstats#5]
Hey Pontus! 

I tried running popstats with the --f3vanilla option and it seems to require four populations to be specified, even though the --f3 correctly asks for 3.

```
$ python2.7 popstats.py --f3vanilla --pops 1,2,3 --file F3_popstats.merged 
Traceback (most recent call last):
  File "/Users/lamnidis/Software/popstats/popstats.py", line 185, in <module>
    poplabel4=poplist[3].split('+')
IndexError: list index out of range


$ python2.7 popstats.py --f3vanilla --pops 1,2,3,3 --file F3_popstats.merged 
#Runs without raising an error.
```

while --f3 runs normally with 3 populations:
```
$python2.7 popstats.py --f3 --pops 1,2,3 --file F3_popstats.merged 
#Runs without raising an error
```

Thank you!
Thiseas

**Comment by pontussk** [comment]
Hi Thiseas,

Thanks, I will fix this in the future, but in the meantime you can enter
the third ('target') population twice. E.g.

python2.7 popstats.py --f3vanilla --pops 1,2,3,3 --file F3_popstats.merged


Best,
Pontus
