### ISSUE TITLE
Defining pops in tfam file

### ISSUE THREAD

**Issue by mujuls** [pontussk/popstats#8]
Hi Ponstuck,

I have a tped file with all autosomes and tfam file with the individuals (286) from 7 different populations. Each of the pops have a specific identifier the consists of a 3 letter pop code and individual identifier e.g KPA_562. I was inquiring how I would use the python script to extract the pops I want to study? The example file in the link you had provided in one of the issues I read is not active.

Thank you.

**Comment by pontussk** [comment]
Hi,

I recommend that you use PLINK to extract individuals from the file http://zzz.bwh.harvard.edu/plink/.

Best,
Pontus
